// <auto-generated />
using System;
using BooksWebApi.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BooksWebApi.Migrations
{
    [DbContext(typeof(BooksApiDbContext))]
    [Migration("20210921212608_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BooksWebApi.Models.Book", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = "B01",
                            Author = "Kutner, Joe",
                            Description = "Deploying with JRuby is the missing link between enjoying JRuby and using it in the real world to build high-performance, scalable applications.",
                            Genre = "Computer",
                            Price = 33.0,
                            PublishDate = new DateTime(2012, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Deploying with JRuby"
                        },
                        new
                        {
                            Id = "B02",
                            Author = "Ralls, Kim",
                            Description = "A former architect battles corporate zombies, an evil sorceress, and her own childhood to become queen of the world.",
                            Genre = "Fantasy",
                            Price = 5.9500000000000002,
                            PublishDate = new DateTime(2000, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Midnight Rain"
                        },
                        new
                        {
                            Id = "B03",
                            Author = "Corets, Eva",
                            Description = "After the collapse of a nanotechnology society in England, the young survivors lay the foundation for a new society.",
                            Genre = "Fantasy",
                            Price = 5.9500000000000002,
                            PublishDate = new DateTime(2000, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Maeve Ascendant"
                        },
                        new
                        {
                            Id = "B04",
                            Author = "Corets, Eva",
                            Description = "In post-apocalypse England, the mysterious agent known only as Oberon helps to create a new life for the inhabitants of London. Sequel to Maeve Ascendant.",
                            Genre = "Fantasy",
                            Price = 5.9500000000000002,
                            PublishDate = new DateTime(2001, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Oberon's Legacy"
                        },
                        new
                        {
                            Id = "B05",
                            Author = "Tolkien, JRR",
                            Description = "If you care for journeys there and back, out of the comfortable Western world, over the edge of the Wild, and home again, and can take an interest in a humble hero blessed with a little wisdom and a little courage and considerable good luck, here is a record of such a journey and such a traveler.",
                            Genre = "Fantasy",
                            Price = 11.949999999999999,
                            PublishDate = new DateTime(1985, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = "B06",
                            Author = "Randall, Cynthia",
                            Description = "When Carla meets Paul at an ornithology conference, tempers fly as feathers get ruffled.",
                            Genre = "Romance",
                            Price = 4.9500000000000002,
                            PublishDate = new DateTime(2000, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Lover Birds"
                        },
                        new
                        {
                            Id = "B07",
                            Author = "Thurman, Paula",
                            Description = "A deep sea diver finds true love twenty thousand leagues beneath the sea.",
                            Genre = "Romance",
                            Price = 4.9500000000000002,
                            PublishDate = new DateTime(2000, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Splish Splash"
                        },
                        new
                        {
                            Id = "B08",
                            Author = "Knorr, Stefan",
                            Description = "An anthology of horror stories about roaches, centipedes, scorpions  and other insects.",
                            Genre = "Horror",
                            Price = 4.9500000000000002,
                            PublishDate = new DateTime(2000, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Creepy Crawlies"
                        },
                        new
                        {
                            Id = "B09",
                            Author = "Kress, Peter",
                            Description = "After an inadvertant trip through a Heisenberg Uncertainty Device, James Salway discovers the problems of being quantum.",
                            Genre = "Science Fiction",
                            Price = 6.9500000000000002,
                            PublishDate = new DateTime(2000, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Paradox Lost"
                        },
                        new
                        {
                            Id = "B10",
                            Author = "O'Brien, Tim",
                            Description = "Microsoft's .NET initiative is explored in detail in this deep programmer's reference.",
                            Genre = "Computer",
                            Price = 36.950000000000003,
                            PublishDate = new DateTime(2000, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Microsoft .NET= The Programming Bible"
                        },
                        new
                        {
                            Id = "B11",
                            Author = "Sydik, Jeremy J",
                            Description = "Accessibility has a reputation of being dull, dry, and unfriendly toward graphic design. But there is a better way= well-styled semantic markup that lets you provide the best possible results for all of your users. This book will help you provide images, video, Flash and PDF in an accessible way that looks great to your sighted users, but is still accessible to all users.",
                            Genre = "Computer",
                            Price = 34.950000000000003,
                            PublishDate = new DateTime(2007, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Design Accessible Web Sites"
                        },
                        new
                        {
                            Id = "B12",
                            Author = "Russell, Alex",
                            Description = "The last couple of years have seen big changes in server-side web programming. Now it’s the client’s turn; Dojo is the toolkit to make it happen and Mastering Dojo shows you how.",
                            Genre = "Computer",
                            Price = 38.950000000000003,
                            PublishDate = new DateTime(2008, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mastering Dojo"
                        },
                        new
                        {
                            Id = "B13",
                            Author = "Copeland, David Bryant",
                            Description = "Speak directly to your system. With its simple commands, flags, and parameters, a well-formed command-line application is the quickest way to automate a backup, a build, or a deployment and simplify your life.",
                            Genre = "Computer",
                            Price = 20.0,
                            PublishDate = new DateTime(2012, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Build Awesome Command-Line Applications in Ruby"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
